### ISSUE TITLE
Betterdiscord makes discord act as a browser

### ISSUE THREAD

**Issue by ShadowCresendo** [bb010g/betterdiscordctl#130] opened 2021-05-22 13:43 UTC
When I install betterdiscord using betterdiscordctl it makes discord say its running in a browser even if its running as an app

I'm running stable on Pop!_OS 20.10

**Comment by ObserverOfTime** [comment] 2021-05-22 13:47
**Duplicate of #96**

**Closed by ObserverOfTime** 2021-05-22 13:47 UTC
