### ISSUE TITLE
how to link?

### ISSUE THREAD

**Issue by a7md8762** [bb010g/betterdiscordctl#119] opened 2021-04-03 11:19 UTC
The Links is Saying No
![Screenshot_20210403_131821](https://user-images.githubusercontent.com/81858682/113476978-3bcd4d80-947f-11eb-969b-bda76ab3da02.png)
How to Fix It?

**Comment by ObserverOfTime** [comment] 2021-04-03 11:33
Duplicate of #96

**Closed by ObserverOfTime** 2021-04-03 11:33 UTC

**Comment by a7md8762** [comment] 2021-04-03 11:53
Man I Don't Understand.
Just How to Fix it??

**Comment by ObserverOfTime** [comment] 2021-04-03 16:49
Use the installer mentioned in that issue.
