### ISSUE TITLE
Better Discord broken (for me) in Linux (Ubuntu LTS 20.04)

### ISSUE THREAD

**Issue by The-W1zzard** [bb010g/betterdiscordctl#99] opened 2021-03-24 09:23 UTC
Hello,
I'm using the Discord snap installed off the Terminal (Version 0.0.14)
The Snap works just fine as the normal discord should do.
As i'm installing Better Discord via the terminal this output is displayed.
After the Install of Better Discord it is apparently in the "Web-mode" and then there is a button for the "App-download".
There is also no Better Discord Menu.

Screenshots: https://imgur.com/a/ww9t9z6

Have a nice day :)

**Comment by szasza221** [comment] 2021-03-24 09:33
Same problem on Arch!

**Comment by ObserverOfTime** [comment] 2021-03-24 09:35
Duplicate of #98.

**Closed by ObserverOfTime** 2021-03-24 09:35 UTC
