### ISSUE TITLE
betterdiscordctl upgrade issue zsh

### ISSUE THREAD

**Issue by Xenfo** [bb010g/betterdiscordctl#97] opened 2021-03-09 13:17 UTC
Downloading betterdiscordctl...
Successfully updated betterdiscordctl.
/usr/local/bin/betterdiscordctl: line 662: syntax error near unexpected token `)'

**Comment by ObserverOfTime** [comment] 2021-03-09 17:08
Use bash.

**Comment by ObserverOfTime** [comment] 2021-03-30 06:34
Actually it does seem to be an issue in bash too.

**Comment by ObserverOfTime** [comment] 2021-03-30 06:47
It looks like the command succeeds anyway and I can't reproduce it on v1.7.1 so I'm closing this again.

**Closed by ObserverOfTime** 2021-03-30 06:47 UTC
Labels: Bug:unresolved
