### ISSUE TITLE
Issue with Rauenzi and JSON

### ISSUE THREAD

**Issue by StarrKiss** [bb010g/betterdiscordctl#103] opened 2021-03-24 18:08 UTC
Hello, I have the same issue as listed here -
https://github.com/bb010g/betterdiscordctl/issues/77
However, when I use the -c flag on the install as reccomended, BetterDiscord does not install AT ALL, and instead just launches normal discord. 
![image](https://user-images.githubusercontent.com/13007697/112362028-fd2adc80-8ca1-11eb-9da8-4f77a8ef55b3.png)
WIth this command.

**Comment by StarrKiss** [comment] 2021-03-24 19:45
What is this a duplicate OF? the issue I linked is solved by doing -c, this issue is not. Hence it's a seperate issue.

**Comment by bb010g** [comment] 2021-05-21 23:30
Does this reproduce with #120?

**Comment by ObserverOfTime** [comment] 2021-05-22 08:40
It's a duplicate of #96, as is almost every other issue since that one, because no matter what options you use it won't work until the aforementioned PR is merged.

**Closed** 2021-05-22 08:41 UTC
Labels: duplicate, upstream:BetterDiscord
