### ISSUE TITLE
Discord Update changed version number

### ISSUE THREAD

**Issue by piks** [bb010g/betterdiscordctl#12] opened 2018-05-01 15:51 UTC
0.0.8 no longer exists as it is now 0.0.9 with latest update, was able to override it with the -m flag

pika@pika-mint ~ $ sudo betterdiscordctl install -s /usr/share -f PTB
Updating asar...
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/pika/.config/discordptb/0.0.8/modules/discord_desktop_core/core.asar'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.exports.readArchiveHeaderSync (/home/pika/.local/share/betterdiscordctl/asar/node_modules/asar/lib/disk.js:69:17)
    at Object.module.exports.readFilesystemSync (/home/pika/.local/share/betterdiscordctl/asar/node_modules/asar/lib/disk.js:95:25)
    at Object.module.exports.extractAll (/home/pika/.local/share/betterdiscordctl/asar/node_modules/asar/lib/asar.js:189:27)
    at Command.<anonymous> (/home/pika/.local/share/betterdiscordctl/asar/node_modules/asar/bin/asar.js:60:15)
    at Command.listener (/home/pika/.local/share/betterdiscordctl/asar/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/home/pika/.local/share/betterdiscordctl/asar/node_modules/commander/index.js:651:12)
    at Command.parse (/home/pika/.local/share/betterdiscordctl/asar/node_modules/commander/index.js:474:21)
ERROR: Failed to unpack core asar.
You may want to install or update nodejs and npm.

additionally: apologize for not having it formatted, tried using a code block but it didn't work

**Comment by piks** [comment] 2018-05-01 15:54
Just noticed there is more than one branch on this now, I'm on the master branch

**Comment by ObserverOfTime** [comment] 2018-05-01 17:24
First of all, you shouldn't be using `betterdiscordctl` with `sudo`.
I can't reproduce this bug, but I can think of a cause.
This is probably caused by the module directory version check picking the lowest version.
So, if for some reason the directory with the old version isn't deleted, but is otherwise empty, this will likely be the result.

**Comment by ObserverOfTime** [comment] 2018-07-03 12:30
@piks This should be fixed now that #11 was merged.

**Closed by ObserverOfTime** 2018-07-03 12:30 UTC
Labels: bug
