### ISSUE TITLE
No error message, but no sign of betterdiscord in the settings.

### ISSUE THREAD

**Issue by ModcoLocko** [bb010g/betterdiscordctl#115] opened 2021-03-29 23:01 UTC
Using flatpack discord on pop os (unbuntu with some minor tweaks) and installed the flatpack package, no sign of better discord tho but no errors while installing.

**Comment by An0nym0us-sh** [comment] 2021-03-30 05:12
Same here with the snap version in (ubuntu with tweaks) 
One error when upgrading
/usr/local/bin/betterdiscordctl: line 662: syntax error near unexpected token `)'

**Comment by Maritsu** [comment] 2021-03-30 05:56
Both happened. No sign all the time, changes Discord to a way less stable version of browser version and sometimes I get @An0nym0us-sh's error

**Comment by ObserverOfTime** [comment] 2021-03-30 06:35
Duplicate of #96 & #97.

**Closed by ObserverOfTime** 2021-03-30 06:35 UTC
